CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    university VARCHAR(150) NOT NULL,
    class VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    mobile VARCHAR(15) NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);